### PR TITLE
2.18.3

### PR DESCRIPTION
**Pull request by VicV**

### CODE REVIEW

**Comment by VicV** [comment]
@ladanazita still can't get past the checks. Its been almost 6 months. Any insight?

**Comment by VicV** [comment]
cc @f2prateek

**Comment by f2prateek** [comment]
@VicV If you can post the output of a succesful build from a local run, we can test ourselves as well and merge this.

**Comment by f2prateek** [comment]
(the idea is to run the tests on multiple computers to verify the build isn't broken in lieu of a CI)

**Comment by VicV** [comment]
Of course it builds on my machine, thats why I'm submitting a PR.

I am having a hard time understanding whats going on in the CI. Could you build for me and tell me if I'm missing something? I'm a bit confused. 

image

**Comment by VicV** [comment]
Yeah, it runs locally just fine. Can you run it on yours and tell me whats going on? 

built

**Comment by f2prateek** [comment]
```
 prateek@Superman-MBP  ~/dev/src/github.com/segment-integrations/analytics-ios-integration-taplytics   pr/11  make clean install build test
2017-04-11 14:33:56.483 xcodebuild[8372:2466504] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ClangFormat.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-04-11 14:33:56.484 xcodebuild[8372:2466504] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Cleaning Pods/Analytics [Debug]
▸ Check Dependencies
▸ Cleaning Pods/Segment-Taplytics [Debug]
▸ Check Dependencies
▸ Cleaning Pods/Pods-Segment-Taplytics_Example [Debug]
▸ Check Dependencies
▸ Cleaning Segment-Taplytics/Segment-Taplytics_Example [Debug]
▸ Check Dependencies
▸ Clean Succeeded
Analyzing dependencies
Fetching podspec for `Segment-Taplytics` from `../`
[!] Unable to satisfy the following requirements:

- `Taplytics (= 2.13.0)` required by `Podfile.lock`
- `Taplytics (~> 2.18.3)` required by `Segment-Taplytics (1.1.0)`

Specs satisfying the `Taplytics (= 2.13.0), Taplytics (~> 2.18.3)` dependency were found, but they required a higher minimum deployment target.
make: *** [install] Error 1
```

If I remove the lockfile:
```
 prateek@Superman-MBP  ~/dev/src/github.com/segment-integrations/analytics-ios-integration-taplytics   pr/11 ●  make install
Analyzing dependencies
Fetching podspec for `Segment-Taplytics` from `../`
[!] Unable to satisfy the following requirements:

- `Taplytics (~> 2.18.3)` required by `Segment-Taplytics (1.1.0)`

None of your spec sources contain a spec satisfying the dependency: `Taplytics (~> 2.18.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
make: *** [install] Error 1
```

Can you paste the output of your local build?

**Comment by VicV** [comment]
I'm seeing this on the Make:

image

But its definitely hosted:
https://cocoapods.org/?q=taplytics

**Comment by f2prateek** [comment]
Cool so regardless of the CI error, it's failing locally too which means we can't merge this. I'll take a look at fixing the changes.

**Comment by VicV** [comment]
Digging deeper here too.

**Comment by f2prateek** [comment]
One thing to not eis we don't really need to change to `s.dependency 'Taplytics', '~> 2.18.3'`. We could just change it to `s.dependency 'Taplytics', '~> 2.13'` which means CocoaPods will automatically use any version > 2.13 upto 3.0 (https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions). This is exactly what we need, assuming Taplytics maintains semantic version and doesn't break the API until 3.0 (though I'm not sure it does given the Android SDK broken APIs without a major version bump).

**Comment by VicV** [comment]
We switched to a proper semantic versioning about 6 months ago, so it should be fine. Switching to a different branch though.

**Pull request closed without merging**
